# Generated by Django 6.0.6 on 2026-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_alter_estimate_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='deadline_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='estimate',
            name='environment',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
