# Generated by Django 6.0.6 on 2026-06-28 18:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_estimate_deadline_days_estimate_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateline',
            name='length',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Comprimento em metros', max_digits=8),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='width',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Largura em metros', max_digits=8),
        ),
    ]
