import uuid
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('core','0001_initial')]
    operations = [
        migrations.CreateModel(name='Customer', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('type', models.CharField(choices=[('person','Pessoa Física'),('company','Pessoa Jurídica')], default='company', max_length=20)),('name', models.CharField(max_length=180)),('legal_name', models.CharField(blank=True, max_length=220)),('document', models.CharField(blank=True, db_index=True, max_length=32)),('email', models.EmailField(blank=True, max_length=254)),('phone', models.CharField(blank=True, max_length=32)),('city', models.CharField(blank=True, max_length=120)),('state', models.CharField(blank=True, max_length=2)),('status', models.CharField(choices=[('active','Ativo'),('inactive','Inativo'),('prospect','Prospect')], default='active', max_length=20)),('notes', models.TextField(blank=True)),('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'))], options={'ordering':['name']}),
        migrations.CreateModel(name='CustomerContact', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=160)),('role', models.CharField(blank=True, max_length=120)),('email', models.EmailField(blank=True, max_length=254)),('phone', models.CharField(blank=True, max_length=32)),('is_primary', models.BooleanField(default=False)),('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer'))]),
        migrations.CreateModel(name='CustomerAddress', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('label', models.CharField(default='Principal', max_length=80)),('street', models.CharField(blank=True, max_length=180)),('number', models.CharField(blank=True, max_length=30)),('complement', models.CharField(blank=True, max_length=120)),('district', models.CharField(blank=True, max_length=120)),('city', models.CharField(blank=True, max_length=120)),('state', models.CharField(blank=True, max_length=2)),('zipcode', models.CharField(blank=True, max_length=20)),('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer'))]),
        migrations.AddIndex(model_name='customer', index=models.Index(fields=['organization','document'], name='customers_c_organiz_cdcf7c_idx')),
    ]
