# Generated by Django 6.0.6 on 2026-06-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_organiz_4213a1_idx',
            old_name='customers_c_organiz_cdcf7c_idx',
        ),
    ]
