# Generated by Django 6.0.6 on 2026-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_c_organiz_cdcf7c_idx_customers_c_organiz_4213a1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_origin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='lgpd_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
