# Generated by Django 6.0.6 on 2026-06-28 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(max_length=120)),
                ('consent_text', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
