# Generated by Django 6.0.6 on 2026-06-28 17:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplier_vehicle'),
        ('customers', '0003_customer_address_customer_lead_origin_and_more'),
        ('estimates', '0003_estimate_deadline_days_estimate_environment'),
        ('sales', '0002_project'),
        ('service_reports', '0002_alter_servicereport_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='risks_reported',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('checklist_completed', models.BooleanField(default=False)),
                ('customer_accepted', models.BooleanField(default=False)),
                ('pending_issues', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('delivered', 'Entregue'), ('pending', 'Entregue com pendência')], default='in_progress', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='customers.customer')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='estimates.estimate')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sales.project')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
    ]
