# Generated by Django 6.0.6 on 2026-06-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_reports', '0003_servicereport_risks_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdelivery',
            name='chk_cleaning_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdelivery',
            name='chk_customer_oriented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdelivery',
            name='chk_finish_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdelivery',
            name='chk_parts_installed',
            field=models.BooleanField(default=False),
        ),
    ]
