import uuid
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('core','0001_initial'), ('customers','0001_initial')]
    operations = [
        migrations.CreateModel(name='AccountReceivable', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('description', models.CharField(max_length=220)),('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),('issue_date', models.DateField(blank=True, null=True)),('due_date', models.DateField()),('paid_at', models.DateTimeField(blank=True, null=True)),('status', models.CharField(choices=[('pending','Pendente'),('paid','Pago'),('overdue','Vencido'),('cancelled','Cancelado')], default='pending', max_length=20)),('reference', models.CharField(blank=True, max_length=120)),('notes', models.TextField(blank=True)),('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='customers.customer')),('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'))], options={'ordering':['due_date']}),
        migrations.CreateModel(name='AccountPayable', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('supplier_name', models.CharField(blank=True, max_length=180)),('description', models.CharField(max_length=220)),('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),('issue_date', models.DateField(blank=True, null=True)),('due_date', models.DateField()),('paid_at', models.DateTimeField(blank=True, null=True)),('status', models.CharField(choices=[('pending','Pendente'),('paid','Pago'),('overdue','Vencido'),('cancelled','Cancelado')], default='pending', max_length=20)),('reference', models.CharField(blank=True, max_length=120)),('notes', models.TextField(blank=True)),('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'))], options={'ordering':['due_date']}),
    ]
