# Generated by Django 6.0.6 on 2026-07-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('saas', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='schools.schoolunit'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='schools.school'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('school', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('academic_year', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('school', 'registration_number'), name='uniq_teacher_registration_per_school_when_filled'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'class_group', 'subject', 'academic_year')},
        ),
    ]
