# Generated by Django 6.0.6 on 2026-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('document_number', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='GuardianStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mãe'), ('FATHER', 'Pai'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('FINANCIAL_RESPONSIBLE', 'Responsável financeiro'), ('EMERGENCY_CONTACT', 'Contato de emergência'), ('OTHER', 'Outro')], max_length=30)),
                ('can_pickup', models.BooleanField(default=False)),
                ('can_view_financial', models.BooleanField(default=False)),
                ('can_receive_messages', models.BooleanField(default=True)),
                ('can_authorize_events', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['guardian__full_name', 'student__full_name', 'relationship'],
            },
        ),
    ]
