# Generated by Django 6.0.6 on 2026-07-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardians', '0002_initial'),
        ('saas', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudentlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.student'),
        ),
        migrations.AddField(
            model_name='guardianstudentlink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student_links', to='saas.tenant'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('school', 'document_number'), name='uniq_guardian_document_per_school_when_filled'),
        ),
        migrations.AlterUniqueTogether(
            name='guardianstudentlink',
            unique_together={('guardian', 'student', 'relationship')},
        ),
    ]
