# Generated by Django 6.0.6 on 2026-07-02 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('saas', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('preferred_name', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=32)),
                ('student_code', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('TRANSFERRED', 'Transferido'), ('SUSPENDED', 'Suspenso'), ('GRADUATED', 'Formado'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='saas.tenant')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('PENDING', 'Pendente'), ('CANCELED', 'Cancelada'), ('TRANSFERRED', 'Transferida'), ('COMPLETED', 'Concluída')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateField(default=django.utils.timezone.localdate)),
                ('exited_at', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.academicyear')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.classgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='saas.tenant')),
            ],
            options={
                'ordering': ['student__full_name', '-enrolled_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('student_code', ''), _negated=True), fields=('school', 'student_code'), name='uniq_student_code_per_school_when_filled'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment_number', ''), _negated=True), fields=('school', 'enrollment_number'), name='uniq_enrollment_number_per_school_when_filled'),
        ),
    ]
