# Generated by Django 6.0.6 on 2026-06-28 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplier_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_name', models.CharField(max_length=180, verbose_name='Nome Fantasia')),
                ('legal_name', models.CharField(blank=True, max_length=220, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=32, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Comercial')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
                ('address', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('business_hours', models.CharField(blank=True, max_length=240, verbose_name='Horário de Atendimento')),
                ('slogan', models.CharField(blank=True, max_length=240, verbose_name='Slogan')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto Padrão de Rodapé')),
                ('default_terms', models.TextField(blank=True, verbose_name='Condições Comerciais Padrão')),
                ('default_estimate_validity', models.PositiveIntegerField(default=7, verbose_name='Prazo Padrão de Validade do Orçamento')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Política de Privacidade')),
                ('terms_of_use', models.TextField(blank=True, verbose_name='Termos de Uso')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Ativo')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.organization')),
            ],
            options={
                'verbose_name': 'Perfil da Empresa',
                'verbose_name_plural': 'Perfis de Empresa',
            },
        ),
    ]
