# Generated by Django 6.0.6 on 2026-07-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=32, verbose_name='telefone')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('legal_name', models.CharField(blank=True, max_length=180, verbose_name='razão social')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('address_line', models.CharField(blank=True, max_length=220, verbose_name='endereço')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Unidade escolar',
                'verbose_name_plural': 'Unidades escolares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('registration_code', models.CharField(max_length=50, verbose_name='código de matrícula')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('grade_name', models.CharField(blank=True, max_length=80, verbose_name='série')),
                ('classroom', models.CharField(blank=True, max_length=80, verbose_name='turma/sala')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('TRANSFERRED', 'Transferido')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('school_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='backoffice.schoolunit', verbose_name='unidade escolar')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('relationship', models.CharField(choices=[('FATHER', 'Pai'), ('MOTHER', 'Mãe'), ('GRANDPARENT', 'Avô/Avó'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('OTHER', 'Outro')], max_length=20, verbose_name='parentesco')),
                ('can_authorize_exit', models.BooleanField(default=True, verbose_name='pode autorizar saída')),
                ('can_receive_notifications', models.BooleanField(default=True, verbose_name='pode receber notificações')),
                ('can_approve_canteen_orders', models.BooleanField(default=False, verbose_name='pode aprovar pedidos da cantina')),
                ('is_primary', models.BooleanField(default=False, verbose_name='responsável principal')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='backoffice.guardian', verbose_name='responsável')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='backoffice.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'Vínculo aluno-responsável',
                'verbose_name_plural': 'Vínculos aluno-responsável',
                'ordering': ['student__full_name', 'guardian__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school_unit', 'registration_code'), name='backoffice_student_unique_registration_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='studentguardianlink',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='backoffice_unique_student_guardian_link'),
        ),
    ]
