import uuid
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('customers','0001_initial')]
    operations = [
        migrations.CreateModel(name='AgentProfile', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=120)),('kind', models.CharField(choices=[('livia','Lívia - Assistente virtual'),('atlas','Atlas - Prospecção'),('policy','Policy Guard'),('custom','Customizado')], max_length=30)),('purpose', models.TextField()),('instructions', models.TextField(blank=True)),('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='AtlasProspect', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('company_name', models.CharField(max_length=180)),('website', models.URLField(blank=True)),('contact_name', models.CharField(blank=True, max_length=160)),('contact_email', models.EmailField(blank=True, max_length=254)),('phone', models.CharField(blank=True, max_length=40)),('city', models.CharField(blank=True, max_length=120)),('state', models.CharField(blank=True, max_length=2)),('source', models.CharField(blank=True, max_length=160)),('score', models.PositiveSmallIntegerField(default=0)),('status', models.CharField(choices=[('new','Novo'),('review','Revisão'),('approved','Aprovado'),('rejected','Rejeitado'),('contacted','Contatado')], default='new', max_length=30)),('evidence', models.JSONField(blank=True, default=dict)),('notes', models.TextField(blank=True))]),
        migrations.CreateModel(name='VirtualAssistantSession', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('channel', models.CharField(default='web', max_length=40)),('visitor_name', models.CharField(blank=True, max_length=160)),('visitor_email', models.EmailField(blank=True, max_length=254)),('visitor_phone', models.CharField(blank=True, max_length=40)),('summary', models.TextField(blank=True)),('status', models.CharField(default='open', max_length=30)),('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentprofile')),('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'))]),
        migrations.CreateModel(name='AtlasEmailDraft', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('subject', models.CharField(max_length=180)),('body', models.TextField()),('to_email', models.EmailField(max_length=254)),('from_email', models.EmailField(blank=True, max_length=254)),('approved_by_human', models.BooleanField(default=False)),('sent_at', models.DateTimeField(blank=True, null=True)),('status', models.CharField(default='draft', max_length=30)),('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='agents.atlasprospect'))]),
        migrations.CreateModel(name='VirtualAssistantMessage', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('role', models.CharField(choices=[('user','Usuário'),('assistant','Assistente'),('system','Sistema')], max_length=20)),('content', models.TextField()),('metadata', models.JSONField(blank=True, default=dict)),('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.virtualassistantsession'))]),
    ]
