import uuid
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('core','0001_initial')]
    operations = [
        migrations.CreateModel(name='ProductCategory', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=160)),('slug', models.SlugField(max_length=180)),('description', models.TextField(blank=True)),('is_active', models.BooleanField(default=True)),('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'))], options={'ordering':['name'], 'unique_together': {('organization','slug')}}),
        migrations.CreateModel(name='Product', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=180)),('sku', models.CharField(blank=True, db_index=True, max_length=80)),('type', models.CharField(choices=[('product','Produto'),('service','Serviço'),('part','Peça'),('accessory','Acessório')], default='product', max_length=20)),('description', models.TextField(blank=True)),('unit', models.CharField(default='un', max_length=20)),('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),('is_active', models.BooleanField(default=True)),('metadata', models.JSONField(blank=True, default=dict)),('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory')),('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'))], options={'ordering':['name'], 'unique_together': {('organization','sku')}}),
        migrations.CreateModel(name='ProductItem', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('kind', models.CharField(choices=[('component','Componente'),('kit_item','Item de Kit'),('accessory','Acessório'),('spare_part','Peça de reposição')], default='component', max_length=30)),('name', models.CharField(max_length=180)),('sku', models.CharField(blank=True, max_length=80)),('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),('notes', models.TextField(blank=True)),('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_items', to='catalog.product')),('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.product'))], options={'ordering':['product__name','name']}),
    ]
