# Generated by Django 6.0.6 on 2026-07-01 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SantanderChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, help_text='UUID gerado pelo navegador e persistido no localStorage.', max_length=64, unique=True, verbose_name='Chave da sessão')),
                ('client_name', models.CharField(blank=True, max_length=160, verbose_name='Nome do cliente')),
                ('client_phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone / WhatsApp')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('client_company', models.CharField(blank=True, help_text='Preenchido se o visitante for de construtora, escritório ou loja.', max_length=180, verbose_name='Empresa / Escritório')),
                ('client_city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('current_state', models.CharField(choices=[('discovery', 'Conversando'), ('collect_name', 'Coletando nome'), ('collect_phone', 'Coletando telefone'), ('collect_email', 'Coletando e-mail'), ('qualified', 'Lead qualificado')], db_index=True, default='discovery', help_text='Posição atual na máquina de estados de coleta.', max_length=30, verbose_name='Estado atual do lead')),
                ('source_page', models.CharField(blank=True, help_text='URL da página em que o visitante abriu o chat.', max_length=500, verbose_name='Página de origem')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Sessão ativa')),
                ('qualified_at', models.DateTimeField(blank=True, help_text='Data/hora em que o lead foi considerado qualificado.', null=True, verbose_name='Qualificado em')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SantanderKnowledgeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pergunta', models.CharField(help_text='A pergunta como o cliente faria (forma natural).', max_length=300, verbose_name='Pergunta / Título')),
                ('resposta', models.TextField(help_text='Resposta curada e aprovada pela equipe.', verbose_name='Resposta')),
                ('tags', models.CharField(blank=True, help_text='Termos separados por vírgula usados na busca por keywords.', max_length=500, verbose_name='Tags / Palavras-chave')),
                ('categoria', models.CharField(choices=[('materiais', 'Materiais (Mármore, Granito, Quartzo)'), ('servicos', 'Serviços (Instalação, Polimento, Medição)'), ('produtos', 'Produtos (Bancada, Pia, Soleira, Ilha)'), ('empresa', 'Empresa (Horário, Localização, Garantia)'), ('processo', 'Processo (Prazos, Pagamento, Entrega)'), ('cuidados', 'Cuidados e Manutenção'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item de Conhecimento',
                'verbose_name_plural': 'Itens de Conhecimento',
                'ordering': ['categoria', 'pergunta'],
            },
        ),
        migrations.CreateModel(
            name='SantanderChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Visitante'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=20, verbose_name='Papel')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='santander_assistant.santanderchatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
